name: firebase_cloud_messaging_backend
description: Send Firebase Cloud Message Messages directly from your flutter or Dart Application.

version: 1.0.0

homepage: https://github.com/lotrofans/firebase_cloud_messaging_backend_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  googleapis_auth: ^1.3.1
  http: ^0.13.4
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0

dev_dependencies:
  build_runner: ^2.1.10
  pedantic: ^1.11.1
  test: ^1.21.1
