name: firebase_cloud_messaging_flutter
description: Send Firebase Cloud Message Messages directly from your flutter or
  Dart Application.

version: 1.0.6

homepage: https://github.com/OttomanDeveloper/firebase_cloud_messaging_flutter

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  collection: ^1.17.2
  googleapis_auth: ^1.4.1
  http: ^1.1.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

dev_dependencies:
  build_runner: ^2.4.6
  lints: ^2.1.1
  test: ^1.24.6
