name: firebase_cloud_messaging_flutter
description: Send Firebase Cloud Message Messages directly from your flutter or
  Dart Application.

version: 1.0.5

homepage: https://github.com/OttomanDeveloper/firebase_cloud_messaging_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  googleapis_auth: ^1.3.1
  http: ^0.13.5
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1

dev_dependencies:
  build_runner: ^2.2.0
  lints: ^2.0.0
  test: ^1.21.4
